### ISSUE TITLE
No ammo left warning on ammo-less weapons

### ISSUE THREAD

**Issue by ShadowK13** [wildj79/foundryvtt-starfinder#103]
Analog melee weapons, like the survival knife, cause a yellow "Knife, survival has no ammunition left!" popup. Not the biggest issue since it doesn't stop you from doing anything, but I wanted to mention it.

**Comment by ShadowK13** [comment]
Discovered in Discord that many items default to 0 in the capacity and usage fields, which causes the issue. If those fields are blank, it works

**Comment by wildj79** [comment]
Should be fixed in pull request #107 which has been merged for the next release.
