### ISSUE TITLE
[Content Submission] Soldier Class

### ISSUE THREAD

**Issue by ShadowK13** [wildj79/foundryvtt-starfinder#104]
[FVTT Soldier.zip](https://github.com/wildj79/foundryvtt-starfinder/files/4949402/FVTT.Soldier.zip)
Contains CRB Soldier features as Feats that link to each other.

**Comment by ShadowK13** [comment]
[Soldier Fix.zip](https://github.com/wildj79/foundryvtt-starfinder/files/4954913/Soldier.Fix.zip)
I updated the base soldier, as I didn't really like the class features naming layout. github doesn't accept json, so I zipped the one file

**Comment by wildj79** [comment]
working on getting this in right now.
