### ISSUE TITLE
[Content Submission] CRB classes

### ISSUE THREAD

**Issue by ShadowK13** [wildj79/foundryvtt-starfinder#121]
Here's the db files for classes and class features. The classes db just replaces the current classes db. the class features needs a new pack in the system json (set to class-features), then that can also be dropped in the packs folder. They should all be linking correctly between sheets.
[CRB Classes.zip](https://github.com/wildj79/foundryvtt-starfinder/files/4992052/CRB.Classes.zip)

**Comment by wildj79** [comment]
Added to development a while back, just never marked it here.
