### ISSUE TITLE
[Content Submission] Spell Lists and a few mistakes

### ISSUE THREAD

**Issue by ShadowK13** [wildj79/foundryvtt-starfinder#122]
[rules.zip](https://github.com/wildj79/foundryvtt-starfinder/files/4997360/rules.zip)

I linked all the spells on the Mystic and Technomancer Spell Lists. I added remaining spells that were in the sfrpg system to the list with short descriptions from aonsrd.

I also found a few spell mistakes while going through them.

Missing Spells: Detect Tech; Dismissal; Resistant Armor, Greater.

Incorrectly Assigned spells:
Modify Memory - Should be Mystic and Witchwarper
Grave Words - Should be Mystic and Witchwarper
Dispel Magic, Greater - Should be Technomancer, Mystic, and Witchwarper

**Comment by wildj79** [comment]
These were added in the latest release.
