### ISSUE TITLE
NPC sheet, every attack seem to add STR mod, even ranged

### ISSUE THREAD

**Issue by KunYuL** [wildj79/foundryvtt-starfinder#126]
![image](https://user-images.githubusercontent.com/26071469/89215035-1f41e400-d585-11ea-954c-4893583596ba.png)

I set up a small arm weapon attack for my NPC, and it will always use the STR mod if I leave the Ability Modifier empty. By default ranged attacks should use DEX mod, and also when making NPCs, typically we don't add the ability mods to attack rolls. We add a custom attack bonus that we pull out of per CR bonus chart, and this bonus is independant of the ability MOD, as opposed to PC who are governed by it.

When looking at the formulae in the screenshot, it's mistakenly adding @abilities.str.mod to any attack roll.

What we need : a field in the Ability Modifier named NONE. I need the option to add none of the ability modifiers and leave that decision to me and my custom made attack roll bonus.

Thank you for your hard work,
Sincerely,
Jules

**Comment by KunYuL** [comment]
![image](https://user-images.githubusercontent.com/26071469/89215186-67610680-d585-11ea-8aa7-a95d09e79f2a.png)

Another screenshot, I meant to show the weapon edit screen

**Comment by wildj79** [comment]
This was actually a fairly easy fix, so it will be included in the next release.

**Comment by wildj79** [comment]
This was fixed in the latest release. As long as the Ability Modifier field is left blank, it won't be added into the roll for an NPC.
