### ISSUE TITLE
Drones have no skills

### ISSUE THREAD

**Issue by Freelancerjw** [wildj79/foundryvtt-starfinder#132]
Maybe I'm just blind and I'm totally overlooking it, but I can't seem to figure out how to get Skills to show up on the Drone's character sheet. Figured I'd post here in case it was a bug. Thanks for all the work you do on this system!

**Comment by CptTwinkie** [comment]
Drones don't come with skills. They either get remote controlled by the player or they have to have mods installed that grant them skills. The foundry sheets work the same way.

**Comment by Freelancerjw** [comment]
One of my players has a stealth drone and starts with the Reactive Camouflage, which gives it a +10 to stealth, though I do suppose that requires being stationary for one round, hmm. There is the Skill Unit and the player chose the Skill Focus feat and it just seemed to make sense that those bonuses would show up on the front page. His drone also has a camera and enhanced senses which allows it to record up to an hour. I suppose I'm thinking it all through like a familiar from 5e haha.

**Comment by CptTwinkie** [comment]
If you add those to the sheet with the modifiers configured then they should appear.

**Comment by Freelancerjw** [comment]
In that case they weren't unless I did it wrong. I'll mess around with it more and get back to you!

**Comment by Freelancerjw** [comment]
I figured it out, ID-10-T error, Haha. Thanks!
