### ISSUE TITLE
Missing feature: mehanic drones can't have skills

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#134]
Hello,

All drones come with at least two skills, either through their "Bonus Skill Unit" and through Skill Unit (Ex). 

Currently the drone sheet always lists "this drone has no skills available" and there is no way to add them. This might be tied to the fact that modifiers are broken on the drone sheet, see #133

**Comment by TimToxopeus** [comment]
Did you add a bonus skill unit on the Features/Drone Mods list?

**Comment by mxvs** [comment]
Ok, so I managed to download the development version of repository to confirm that the "Class features" compendium where the bonus skill unit is supposed to be found is NOT present in 0.3.5, which essentially makes the Drone Sheet in 0.3.5 unusable as you can't add any of the required features (chassis, etc...) for the sheet to function properly. I guess you can close the issue since it will be fixed when 0.3.6 will eventually be released. In the future I would advise testing that required functionality is actually present before release (parts of a feature) :-)

**Comment by TimToxopeus** [comment]
It does work, you just have to add and edit the items manually. Just open the features tab, and click on the Add button, then configure it. Alternatively, go to the Items sidebar, create item, and then drag the item manually onto the drone sheet.

If this bit of manual work renders a feature unusable, feel free to contribute by submitting a pull request with compendium entries in the future. :-)
