### ISSUE TITLE
Weapon capacity not decreasing when attacking

### ISSUE THREAD

**Issue by Kezzei** [wildj79/foundryvtt-starfinder#137]
When making an attack with a weapon that has charges programmed and usage set, the capacity does not decrease in the character sheet. When the attack occurs, it shows the ammo decrease in the chat window, but it isn't saved and actually reflected in the owner's sheet. Subsequent attacks always show the initial charge less the attack. v

Example:

Created Azimuth laser pistol, capacity 20 / 20, usage 1 / 20 (or 1 / blank, or anything you want for testing purposes)
Assigned item to player.
Player makes attack.
Text in chat shows 19 /  20 charges.
Character sheet still says 20 / 20.
All future attacks show 19 / 20.

**Comment by TheMimski** [comment]
I had the issue too, and solved it randomly when importing a statblock with the NPC importer module.
It works if you write 1/shot for the usage. I think there are a few other phrases that work, but I couldn't find any documentation on that yet.

**Comment by Kezzei** [comment]
Can confirm, 1 / shot works! Thanks!

**Comment by wildj79** [comment]
Yeah, that's my bad. The second field for usage is the "per" field, so it should be read "use 1 cartridge/charge/bullet/arrow/etc _per_ shot". The two words here that matter for ammo consumption are "shot" and "round" (spelled exactly like that, casing matters). But, this has been changed in the upcoming release to be a drop down box, so it should be clearer what the intent behind this field is.

**Comment by wildj79** [comment]
This should be clearer in the new release. Closing for now, but we can revisit this if it becomes necessary.
