### ISSUE TITLE
Active Feat incorrect chat text

### ISSUE THREAD

**Issue by Kezzei** [wildj79/foundryvtt-starfinder#140]
When creating an active feat with a non-combat/non-damage Action Type (such as Healing), the chat flavor text still shows the button for the roll as "Damage", and the subsequent chat for the actual roll says "Damage Roll"

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Active Feat incorrect chat text](https://trello.com/c/Hgiz3AIX/36-active-feat-incorrect-chat-text)

**Comment by wildj79** [comment]
Fixed in current stable release v0.5.1.0
