### ISSUE TITLE
Weapon critical damage formula not used

### ISSUE THREAD

**Issue by Kezzei** [wildj79/foundryvtt-starfinder#141]
Regardless of what you enter into the Critical Damage Formula for a weapon, the attack always rolls double damage.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Weapon critical damage formula not used](https://trello.com/c/kivSctxM/37-bugz-weapon-critical-damage-formula-not-used)

**Comment by wildj79** [comment]
Fixed in current release.
