### ISSUE TITLE
Refactor Starship sheets

### ISSUE THREAD

**Issue by wildj79** [wildj79/foundryvtt-starfinder#155]
Now that Starship Operations Manual is out, it's time to revisit starship sheets and consider a complete refactor.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Refactor Starship sheets](https://trello.com/c/UAWcphoM/45-feat-refactor-starship-sheets)

**Comment by TimToxopeus** [comment]
I'd say they've been pretty revisited at this point. :-)
