### ISSUE TITLE
[FEAT] Add Item Hardness/Save/HP Tracking to Item (Equipment) sheets.

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#161]
As titled. Very useful to have around when the game includes the frequent use of Sunder maneuvers, etc.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] dd Item Hardness/Save/HP Tracking to Item (Equipment) sheets.](https://trello.com/c/I4UKyfZH/54-feat-dd-item-hardness-save-hp-tracking-to-item-equipment-sheets)

**Comment by TimToxopeus** [comment]
This will be adressed with the 0.5 release.

**Comment by wildj79** [comment]
Fixed in current release.
