### ISSUE TITLE
No way to increase SP in the Effects Section of Character Sheet

### ISSUE THREAD

**Issue by GreyAngelKing** [wildj79/foundryvtt-starfinder#162]
While You can increase SP in the Modifiers Section you cannot assign a reference Value like the Characters Level when you do so. it defaults to a 0 after you save. 

There is no Sp Attribute in the Effects Section (or they might be misnamed) so you cannot add increase Stamina point Maximum there where it accepts a reference Value.

Minor issue has a work around by manually adding it Sp maximum through the Modifiers any time it may change. 

ability to use reference values in the modifiers or adding SP maximum and minimum attributes to effects would fix however.

**Comment by TimToxopeus** [comment]
You can set the modifier type to Roll Formula, and then you can enter @data.details.level as modifier value. Does this fix the problem?

**Comment by GreyAngelKing** [comment]
I could smack my forehead right now. yeah that works completely didnt even think about using the Roll Formula format to enter a reference value many thanks
