### ISSUE TITLE
Detect Tech Spell missing from compendium

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#163]

**Comment by CptTwinkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Detect Tech Spell missing from compendium](https://trello.com/c/iqlZ5Mwz/57-bugz-detect-tech-spell-missing-from-compendium)

**Comment by wildj79** [comment]
Fixed in commit 42e31a4d9c24ccb544e03edb6081f20b1f6ed65a
