### ISSUE TITLE
[BUGZ] Mending spell does 1f4 healing

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#169]

**Comment by CptTwinkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Mending spell does 1f4 healing](https://trello.com/c/5CiYBrnR/61-bugz-mending-spell-does-1f4-healing)

**Comment by TimToxopeus** [comment]
Fixed for the next release.
