### ISSUE TITLE
Accurate Monster pictures for Aliens Compendium

### ISSUE THREAD

**Issue by GreyAngelKing** [wildj79/foundryvtt-starfinder#174]
Have been reading the Trello board I know that an Aliens Compendium is in the works, however since i cannot find a way to message anyone working on this project i had to ask a question here. will the pictures for the aliens be accurate to what they represent? or will they be general icons I have been working on creating a library of Transparent Background pngs of all the aliens as they look in the Alien Archive books. and id be willing to share them with you as i finish them.

**Comment by CptTwinkie** [comment]
There are copyright/licensing issues with using Paizo's artwork. I'm not really aware of much art from them that isn't copyrighted. Creature icons will have to use either something created for the system or something that we can get a license for or official approval for use in the system.

Feel free to discuss with us on the FoundryVTT Discord in the **#starfinder** channel 
https://discordapp.com/invite/DDBZUDf

**Comment by wildj79** [comment]
Using the official Piazo artwork for the alien compendiums is going to be a hard no, unfortunately. There use isn’t covered by the OGL and also not covered by Paizo’s community use policy. We just can’t use them from a legal standpoint.
