### ISSUE TITLE
Powered Armor Missing From Equipment Compendium

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#176]
No details to add
![image](https://user-images.githubusercontent.com/2079751/92409819-3787be80-f142-11ea-8c97-c3b5cf3127e4.png)

**Comment by CptTwinkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Powered Armor Missing From Equipment Compendium](https://trello.com/c/n4LMffOD/63-powered-armor-missing-from-equipment-compendium)

**Comment by TimToxopeus** [comment]
Power armor has been added to the compendium and will be released with 0.5.

Also, searching compendium for power wont turn up power armor, none of the power armors have power in their name. :-)
