### ISSUE TITLE
[FEAT] Add 'Unfriendly' and 'Helpful' as Token Dispositions.

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#180]
As titled, to reflect CRB attitudes properly. To encapsulate the 5 Attitude Tiers outlined under the Social Skills.

They could be colored (on Hover) something like:
- Helpful (Dark Green)
- Friendly (Light Green)
- Indifferent (Yellow)
- Unfriendly (Orange)
- Hostile (Red)

With perhaps Light Blue being reserved for Allied PCs, and Dark Blue for Owned/Controlled PCs.

**Comment by wildj79** [comment]
This is really more of a general foundry issue and not so much a system specific thing. Though I like the idea, I think this would be a better fit for not only a module, but a general use module that is system agnostic.
