### ISSUE TITLE
Item Rolls returning a promise.

### ISSUE THREAD

**Issue by Kekilla0** [wildj79/foundryvtt-starfinder#184]
Would like basic item rolls to return a promise to facilitate macro writing.

Basically the ability to have this code :
`let attack = await item.rollAttack({event});
 if(attack.total > target.eac)
 {
  item.rollDamage()
 }`
or something similar. That way the macro will wait until the dialog is complete and the roll has been rolled before moving onto the conditional statement and erroring.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Item Rolls returning a promise.](https://trello.com/c/9gMrW87O/69-feat-item-rolls-returning-a-promise)

**Comment by wildj79** [comment]
Fixed in https://github.com/wildj79/foundryvtt-starfinder/commit/e6968e060ed1ea975cc246d71bafdfa42758f6de. Will be available in next release.
