### ISSUE TITLE
Not require event for item rolls

### ISSUE THREAD

**Issue by Kekilla0** [wildj79/foundryvtt-starfinder#185]
change 
`item.rollAttack({event});`
to 
`item.rollAttack();`
and pretty much assume if the event is not passed that the executer wants to see the dialog.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Not require event for item rolls.](https://trello.com/c/UnlcztAW/70-feat-not-require-event-for-item-rolls)

**Comment by wildj79** [comment]
Fixed in 5207da0. Will be in next release.
