### ISSUE TITLE
Add custom attribute option for skills

### ISSUE THREAD

**Issue by H0m3SQuashV2** [wildj79/foundryvtt-starfinder#190]
Hello! I have a player who is playing a biohacker, but not in system as of yet which is fine, so I added it and went thru all the steps. Something unique to a Biohacker tho is they get to choose studious which allows them to make Perception checks with Int or they can take instinctive which allows them to make Life Science and Physical Science I believe with Wis. I dont see a way to change that at all on the sheet though.

**Comment by wildj79** [comment]
Right click on the skill. This will be bring up a dialog. You should be able to change the linked ability there.

**Comment by H0m3SQuashV2** [comment]
Thanks for the reply yea I happened to notice it last night. I completely
looked over it! Thank u again!

**Comment by wildj79** [comment]
No problem, glad you were able to figure it out 😉
