### ISSUE TITLE
Spells are in the inventory tab for NPCs

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#193]
![image](https://user-images.githubusercontent.com/2079751/95042403-0d420600-06da-11eb-9a0c-9027af8257ba.png)

**Comment by CptTwinkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Spells are in the inventory tab for NPCs](https://trello.com/c/3itlUPuo/84-bugz-spells-are-in-the-inventory-tab-for-npcs)

**Comment by wildj79** [comment]
I just looked at this in the current version (v0.6.2.0), and it's seems to be working. Not sure when this was fixed, but it looks like it was.
