### ISSUE TITLE
Damage Rolls won't work

### ISSUE THREAD

**Issue by smarschollek** [wildj79/foundryvtt-starfinder#199]
FoundryVTT **0.7.4**
Starfinder     **0.5.1.0**
Active Modules **0**

Any damage roll leads to an error "Syntax error: Unexpected token '}'.
It looks to me as the formula for damage is wrong because it end with a + sign.

![image](https://user-images.githubusercontent.com/15954201/96560131-2ba12780-12be-11eb-9ebc-4abf6881d097.png)

**Comment by wildj79** [comment]
v0.5.1.0 is incompatible with the v0.7.x series of foundry. We are waiting for v0.7.5 (witch will be the next stable version) to release a compatible version. You’ll need to downgrade foundry to version 0.6.6 for now.
