### ISSUE TITLE
SRO race getting Dexterity bonus instead of Strength

### ISSUE THREAD

**Issue by marcuslma** [wildj79/foundryvtt-starfinder#200]
In Races compendium, there is two SRO races available, SRO and SRO (small).
I suppose that SRO should receive the strength bonus, but it is getting the dexterity bonus.
I also noticed that the size is incorrect too, for the default SRO the size should be medium.

**Comment by ThroughlyDruxy** [comment]
Submitted PR correcting all playable races from all books. This issue is resolved.
