### ISSUE TITLE
Class/Race/Theme entries in the features tab are broken in 0.7.5

### ISSUE THREAD

**Issue by IanBacklund** [wildj79/foundryvtt-starfinder#202]
Add a class/Race/theme to a character sheet. Try clicking on it in the sheet. Clicking on the name does not expand to display more info. Clicking on the icon does not send it to chat. There is an error in the console when you click:
![image](https://user-images.githubusercontent.com/3959713/96824397-8d0ee680-13e3-11eb-96c3-86ddc74056ea.png)

**Comment by wildj79** [comment]
Issue confirmed. I'll be pushing out a hotfix for this in a few minutes.

**Comment by wildj79** [comment]
Fixed in current release.
