### ISSUE TITLE
Sheets bugged after version update

### ISSUE THREAD

**Issue by marcuslma** [wildj79/foundryvtt-starfinder#204]
The following is happening to me after the foundry update to 0.7.5 and the starfinder system update to 0.6.0/0.6.1
I tryed to reinstall the system, to reinstall the whole foundry, create new world, but it continues to happen.

![image](https://user-images.githubusercontent.com/5174608/96885050-98502980-1458-11eb-8554-b61ad14f2c33.png)

**Comment by wildj79** [comment]
Open up your devloper console on your browser (hit F12 on windows or linux, cmd+opt+i on a mac), and look for errors. Usually this happens when some of the data for an actor gets corrupted or is missing.

**Comment by wildj79** [comment]
I should have added that you should post those errors here ;)

**Comment by marcuslma** [comment]
Hello, @wildj79 
Thanks for your response.
Yes, there is errors on my browser console.

![image](https://user-images.githubusercontent.com/5174608/96911604-71edb680-1477-11eb-9b80-a7e6ab2570ad.png)

**Comment by marcuslma** [comment]
The manual installation worked, as you suggested. Closing this issue. Thanks a lot!
