### ISSUE TITLE
Roll Error Handling

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#205]
Attack Rolls
- Errors are silent leaving the player in confusion

Damage Rolls
- Errors are silent leaving the player in confusion
- The roll dialog (if opened) cannot be closed...ever

**Comment by wildj79** [comment]
Are you on the current version of both Foundry and starfinder?

**Comment by CptTwinkie** [comment]
STR

1. Remove value from appropriate text box
2. Roll the matching roll
3. Profit from your mistakes

**Comment by wildj79** [comment]
Figured this one out after a conversation on Discord.

So, if a damage formula for a weapon is added but left blank, when the damage button is pressed it will throw this error in the console:

![image](https://user-images.githubusercontent.com/2126857/96915919-7791cf00-146c-11eb-976e-1eaddc3f4de9.png)

Also, setting the Attack Roll Bonus to an empty field shows a `null` value in the roll formula on the chat card. 

![image](https://user-images.githubusercontent.com/2126857/96916095-b32c9900-146c-11eb-9106-ecdadfc2bb4a.png)

**Comment by wildj79** [comment]
Fixed in a feature branch. Will be merged into development in time for next release.

**Comment by wildj79** [comment]
This should be fixed now in the current release. We can reopen if we're still having issues.
