### ISSUE TITLE
Creation spell image looks like fusion

### ISSUE THREAD

**Issue by ThroughlyDruxy** [wildj79/foundryvtt-starfinder#208]
![image](https://user-images.githubusercontent.com/31712348/97100183-f1cd7980-164d-11eb-8f01-eb467d7fa57d.png)

Basically the spell creation has its icon that appears like a fusion rather than a spell.

**Comment by wildj79** [comment]
If you've got a suggestion for a better image, we're all ears. At this point, though, I would prefer to use an image that already exists in the system and not add any additional images.
