### ISSUE TITLE
Negative Armor Class modifier is added instead of being subtracted

### ISSUE THREAD

**Issue by saffron-sd** [wildj79/foundryvtt-starfinder#213]
Negative Armor Class modifier is added instead of being subtracted.

Tested on the 0.6.2 release version.

To reproduce add a modifier that lowers Armor Class, it could be done by adding a condition (Exhausted or Fatigued)

![image](https://user-images.githubusercontent.com/69874882/98823362-46386d80-2432-11eb-8062-2364f3234768.png)

**Comment by wildj79** [comment]
We've been able to confirm that this is an upstream issue in the current version of the Foundry VTT. We've been told that a new release is coming in the next few days, so hopefully the issue will be fixed then.

**Comment by wildj79** [comment]
This was fixed in a core update.
