### ISSUE TITLE
PC Actor Sheet Locked up Unable to open up

### ISSUE THREAD

**Issue by WaterpoloBlock** [wildj79/foundryvtt-starfinder#222]
Player was updating their character (Actor) sheet when it immediately closed on them, they were unable to open it up again. 

As the GM, I was unable to open up the character sheet I tried the following to fix the issue:
1. Duplicate the character/actor sheet, duplicate had the same issue.
2. Export the character sheet and import it into another character sheet, issue followed.

I was able to create another actor sheet for the player in question to use. 

Attached file is an export of the locked up actor sheet, had to put it into a .zip since Github doesn't support JSON files to be attached. 
[fvtt-Actor-Call-I.zip](https://github.com/wildj79/foundryvtt-starfinder/files/5611127/fvtt-Actor-Call-I.zip)

**Comment by TimToxopeus** [comment]
Hi, thanks for the report and the json file.

I have looked at and found the problem. The player dragged a drone chassis onto a player character sheet, which causes an error in the class automizations because we used the same variable for classes and chassis.

Good catch!

**Comment by WaterpoloBlock** [comment]
Thank you for replying so quickly and your insight.
