### ISSUE TITLE
Damage Type Values (incomplete feature, suggestion)

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#23]
Currently, selecting a damage type in an attack roll does not actually affect the output in the chat window at all.
Additionally, you cannot select multiple damage types within a single attack (as is often necessary within the system).

I suggest allowing multiple damage types to be selected per attack, and for the final damage value to be divided between the chosen types as intended.

Lastly, I believe entering a space for an Icon to be used to represent the damage types on output. There's a handful of great ones in the recent game dev icon set I could hand over for the purpose.

**Comment by wildj79** [comment]
This is a known issue that I'm hoping to address in the next couple of releases. I think just adding the combined damage types to the existing drop down would be sufficient for now. Actually passing on that data to the chat card will be a couple of releases after that most likely.

I'll have to consider the icon suggestion a little further. On one hand, it's an extra piece of data that has to be added to the data structure. But, on the other it does add flavor to the damage types. But, I'd need to consider a good way to do this for attacks with multiple damage types.

**Comment by JayBWalker** [comment]
Could I suggest doing the same thing for the icons? Combine two (theoretically) existing ones into a diagonally-split icon containing two triangles each of 50% of the individual icons when a dual-damage type scenario appears.

**Comment by wildj79** [comment]
That's probably how it would have to be done. There wouldn't be an easy way to assign multiple images to one value, so a split icon would have to do. But, I'd leave that to an artist that wanted to do it.

**Comment by wildj79** [comment]
This will be partially implemented in the next release. I parsed the AoN, and found all of the currently possible damage type combinations and added them to the damage type drop down. It still doesn't do anything, but at least the data is there. Actually outputting the damage type on the chat card will come in a later release.

**Comment by wildj79** [comment]
Partially implemented in #49 .

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Damage Type Values (incomplete feature, suggestion)](https://trello.com/c/pY0SLGhr/42-feat-damage-type-values-incomplete-feature-suggestion)
