### ISSUE TITLE
Attack Roll Chat Flavour not showing

### ISSUE THREAD

**Issue by LotsOfLore** [wildj79/foundryvtt-starfinder#235]
Hi, I saw that in one of the latest releases a line saying "Weapon attack chat flavor now included in the attack roll chat card." was mentioned. I just checked it out and I don't see the chat flavour showing anywhere, either in the attack roll chat card, or in the item's chat card. 
Using: Foundry 0.7.8, latest release of Starfinder system, starfinder, Custom Starfinder chat card enabled, Chrome (updated)

**Comment by TimToxopeus** [comment]
This has been fixed with the release of Starfinder v0.8.1.
