### ISSUE TITLE
Item sometimes disappears when writing formula in the Saving Throw (details)

### ISSUE THREAD

**Issue by LotsOfLore** [wildj79/foundryvtt-starfinder#236]
This is a bug that I saw before happing with spells. It now seems to happen for me with weapons: sometimes if you put a formula in the DC space and close the item card, it disappears. Then if you drag another item in the inventory and delete it, the previous items appears once again. 

(Weird witchwarper magic at play for sure)

**Comment by TimToxopeus** [comment]
Save DC system has been overhauled a while back, which resolved this ticket. :) Closing it now.
