### ISSUE TITLE
Wealth calculation doesn't seem to include certain item types

### ISSUE THREAD

**Issue by supernovajm** [wildj79/foundryvtt-starfinder#237]
Tested on sfrpg v0.7.1.4, FoundryVTT v0.7.7

**Steps to reproduce:**

1. Drag an armor upgrade to a PC that has a credit value
2. Whether or not that upgrade is slotted into armor, the value of the armor upgrade is not updating the player's wealth.

Overall, the Item types that did not calculate into wealth are

- Weapon Accessory
- Armor Upgrade
- Hybrid
- Magic

See screenshot. Armor upgrade has a value of 250 credits, but the wealth shows as 0
![image](https://user-images.githubusercontent.com/24704061/103181288-98601180-486d-11eb-9f15-b53e2561ab60.png)

**Comment by mxvs** [comment]
I was about to post a similar issue for this problem, can confirm I'm having the same issue with the same versions of the system and Foundry.

**Comment by TimToxopeus** [comment]
Confirmed, it is an easy fix, thanks for the report!
