### ISSUE TITLE
Drift Engines incorrectly costing PCU usage on Starship sheet

### ISSUE THREAD

**Issue by the-cheldog** [wildj79/foundryvtt-starfinder#251]
Starship Drift Engines require a minimum power rating for a Power Core but do not actually cost any PCU usage. The Starship Sheet currently acts as if the Drift Engine is using up the power. Current fix on the user side is to just uncheck the "is powered" toggle in the details of the drift engine.

**Comment by TimToxopeus** [comment]
That is why the "Is Powered' checkbox is there. The Drift Engines are considered switched off until you need them, in which case you have to unpower your Thrusters for 1 minute, and power up the Drift Engine.

Unchecking the "is powered" toggle is the correct expected player action in this situation.
