### ISSUE TITLE
Starships do not gain AC from NPC crew piloting ranks

### ISSUE THREAD

**Issue by the-cheldog** [wildj79/foundryvtt-starfinder#252]
As the title says, ships should be gaining a bonus to AC based on the pilot's ranks in Piloting but when NPC Crew is checked, the AC is unaffected by Piloting ranks. Works as intended with Player Character pilot.

**Comment by TimToxopeus** [comment]
Issue found, and fixed, ready for the next release.
I also discovered I was using the wrong data field for storing if a ship was an NPC ship, so the checkbox for is NPC crew will be reset for your ships. The crew data will be safe, so all you will have to do is recheck the box.
