### ISSUE TITLE
No dropdown on Starship Sheet for Weapons (Turret) Critical Damage

### ISSUE THREAD

**Issue by the-cheldog** [wildj79/foundryvtt-starfinder#253]
As a tagalong to this, when selecting the Gunner Actions, there is no drop down to select the Turret either. I realize that the Turret has to fire into a certain Quadrant but for purposes of your Turret taking critical damage you would need to be able to select the Turret for that to apply to the roll.

**Comment by ElroTheOnk** [comment]
I believe the current implementation is correct as turret weapons don't suffer critical effects independently; they are considered critically damaged if any arc's weapon is critically damaged [CRB p321 in the crit dam table: "a turret counts as being in all arcs"].

**Comment by the-cheldog** [comment]
Yes, you are correct, This was my own misunderstanding of the rules. I will close the issue!
