### ISSUE TITLE
Target Lock incorrectly gains a "piloting bonus"

### ISSUE THREAD

**Issue by ElroTheOnk** [wildj79/foundryvtt-starfinder#254]
Looks like TL currently gains a "piloting bonus", presumably from the frame's maneuverability in addition to that from the pilot's skill ranks - I don't think this is correct per CRB. Hovering over TL on the starship sheet gives:

Base 10; _Piloting Bonus 1_; Pilot Skill Bonus 7; Mk 6 defenses 6

(This isn't just a mislabelled size bonus: the ship is medium-size, and using a Huge ship correctly applies a -2 "Size modifier" penalty.)

"TL = 10 + the pilot’s ranks in the Piloting skill + the ship’s bonus from defensive countermeasures + modifier based on the ship’s size + penalty from the ship’s armor + bonuses and penalties from successful or failed stunts and actions"

**Comment by TimToxopeus** [comment]
Thanks, confirmed mistake in implementation. I have removed the piloting bonus from the TL calculation, and also fixed TL calculation not taking NPC piloting ranks into account.
