### ISSUE TITLE
Item containers no longer working 

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#256]
Hello,

In version 0.8.1 I can no longer add one item (like a weapon fusion) to another item (like a weapon). 

To reproduce:

See following (hidden) YouTube video with all steps: https://www.youtube.com/watch?v=-MhXodN0KN4&feature=youtu.be

1. Create empty 0.8.1 world with no modules
2. Create Test Actor PC
3. Import items (ex. "Taclash, standard" weapon, "Hindering" weapon fusion )  from compendium
4. Drag weapon to character sheet
5. Try to drag fusion on top of weapon

Result: Fusion ends up in main inventory. 
Expected result: Fusion is added to the weapon.

This issue does NOT occur when I manually rollback my Starfinder version to 0.7.1.4 and try to perform the same action in the same world.

Thanks for looking into it!

**Comment by TimToxopeus** [comment]
Thanks for your report. I have confirmed the bug with dragging items onto containers from compendium, and I have submitted a fix for it moments ago.
Workaround until it gets released is to drag it onto the character sheet, and once it is added to the inventory to then drag it into the container. :)
