### ISSUE TITLE
Equipment needs an equip box in the inventory pane

### ISSUE THREAD

**Issue by msbranin** [wildj79/foundryvtt-starfinder#265]
Equipment needs an equip tick box in the inventory window Just like armor and weapons have so that you do not have to edit the item every time you want to equip it. It will make it easier to use items that have equip mods as you can activate them just by equipping the item.

**Comment by TimToxopeus** [comment]
I have added support for a checkbox "equippable" to the system just a moment ago. All existing item json files for items of the type "weapon", "shield", and "equipment" need to have this new flag set. All items that are supposed to be equippable also need to have it set. It defaults to false if not set.

**Comment by TimToxopeus** [comment]
All easy-to-scan compendium items have been updated, this goes for armor, weapons, shields, and backpacks.

Any equippable compendium items that are not equippable by default can be individually reported and fixed appropriately.
