### ISSUE TITLE
Dragging items from the Item Directory onto other items does not work

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#269]
Hello,

I'm having the same issue as the one that was partially fixed in #256 See the original issue for a video and more details. 

Essentially: 

This problem is fixed for items coming straight from the compendium, but the same behavior is still broken for items coming from the worlds own "Item Directory". If you import an item from the compendium to your world and then drag it from the 'Items Directory' unto an item with a container on a sheet, it drops into general inventory instead of in the item container. 

If you import an item from a compendium A, then drag that item back into another compendium B, and then try to drag the item from B onto the sheet it also breaks. It looks like as soon as the item is imported it fundamentally changes behind the scenes.

Max

**Comment by TimToxopeus** [comment]
Fixed it, it turned out to be caused by the fix for the compendium issue, where I made some general inventory clean-up, but missed a specific codepath in my tests.
