### ISSUE TITLE
Feats with limited uses are not counting usage

### ISSUE THREAD

**Issue by supernovajm** [wildj79/foundryvtt-starfinder#270]
**Current Behavior:**
A feat that has limited uses (ex: 1/1 per long rest) does not count down when the ability is used.

**Expected Behavior:**
Activating the feat should use one remaining use, and should alert if there are no uses left.

**More information:**
![image](https://user-images.githubusercontent.com/24704061/107128632-368fc000-688d-11eb-833b-94067d06cdc3.png)

**Comment by TimToxopeus** [comment]
Fixed it. :)
