### ISSUE TITLE
Armor penalty check crashing when unequipping armor

### ISSUE THREAD

**Issue by IsraelBellavista** [wildj79/foundryvtt-starfinder#274]
I've found that if a character has a heavy armor and I create a modifier that adds an Armor check penalty value only for heavy armors, then I unequip the armor, there is an error and I can't open the character sheet. It doesn't happen if the modifier is applied both to heavy and light armor.
Taking a quick look at the crash and the code (**module/rules/actions/actor/calculate-skill-armor-check-penalty.js** line 27), it seems that the since the armor is unequipped value for the "armor" parameter is null.
Hope this helps!
![Error01](https://user-images.githubusercontent.com/63868469/107159678-ecdccd80-6991-11eb-8db9-4b3fe846fa64.png)

**Comment by TimToxopeus** [comment]
Reproduced, and fixed, thanks! :)
