### ISSUE TITLE
Starship Combat: Power Core critical Damage applies wrong penalties to all actions

### ISSUE THREAD

**Issue by franss22** [wildj79/foundryvtt-starfinder#275]
From CRB pg. 321, or from [https://www.aonsrd.com/Rules.aspx?ID=200](url):
critical damage conditions affecting a ship's power core only partially affect the rest of the ship. However, the way it is implemented right now makes it imposible to have these partial modifiers.
Right now, a glitching, or malfunctioning power core gives the same -2 or -4 penalty to all actions. However, it should give this penalty only to power core actions (except patch it and hold it together), and, to the rest of the actions, give no penalty at glitching, a -2 penalty at malfunctioning, and a -4 penalty if its wrecked.

**Comment by TimToxopeus** [comment]
Fixed the issue, thanks for the report!
