### ISSUE TITLE
Turn an NPC into a PC (or vice-versa)

### ISSUE THREAD

**Issue by nullpunktTUD** [wildj79/foundryvtt-starfinder#276]
Maybe I am just missing something, but is there any way to turn an actor that uses the NPC sheet into an actor that uses the PC sheet?

**Comment by TimToxopeus** [comment]
There is no way to turn NPC actors into PC actors, or vice versa. It's not an easy change-the-type affair either, their data structures are quite different.

I think this is a good idea for a module though. :-)

**Comment by wildj79** [comment]
I'll also point out that in Starfinder, player characters and non-player characters follow a very different set of rules for construction. There isn't always going to be a one to one relationship between NPC abilities and PC abilities, skill ranks, ability scores, etc... Considering the disparity between the two sets of construction rules, this is kind of a tall order, and not something that we will tackle in the core system.
