### ISSUE TITLE
Spell slot usage selection is set to upcasting, rather then downcasting.

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#281]
When casting spells, the prompt that appears allows the user to cast at a different spell level. However currently it only allows the spell to be upcast, which the vanilla ruleset only allows downcasting for variable level spells.
Either a reverse of this should be implemented to lessen the confusion. or allow the selection for all available slots, for Homebrew/3rd party spells that may upcast.

Edit: It was just pointed out to me that technically you can use higher spell slots then the spell, with no benefit except if out of other spell slots. So allowing all selections seems the better option.

It has been suggested that Wildj79 should be put on this by Deepflame

**Comment by TimToxopeus** [comment]
I have overhauled the spellcasting a while ago, that has resolved this ticket.
