### ISSUE TITLE
Equipment Compendium Type issue

### ISSUE THREAD

**Issue by DeimosJ** [wildj79/foundryvtt-starfinder#297]
A number of armors in equipment.db have the wrong Type string, it appears that the type is capitalized where it should be lower case
 e.g.
Clearweave I: `"armor":
        {
            "type": "Light",
            "eac": 3,
            "kac": 3,
            "dex": 5,
            "acp": 0,
            "speedAdjust": 0
        },`
Kasatha microcord IV: `        "armor":
        {
            "type": "light",
            "eac": 13,
            "kac": 15,
            "dex": 5,
            "acp": -1,
            "speedAdjust": 0
        },`

From what i can see it is an issue for a number of Light and Heavy types.

**Comment by rrenna** [comment]
I'll be adding validation to our data entry steps for this, though the manual labour of fixing it will still have to be done. Thanks for calling this out.

**Comment by rrenna** [comment]
Data is being fixed now.

**Comment by wildj79** [comment]
Updated in the current release.
