### ISSUE TITLE
Quicker way to roll attacks and damage

### ISSUE THREAD

**Issue by HubbeKing** [wildj79/foundryvtt-starfinder#30]
Currently, if one defines or adds a weapon to a character sheet, in order to roll attacks or damage with that weapon, one must first click the weapon. This posts a link into the chat, with buttons for rolling attack or damage. This means that in order to attack with a character, you first have to open the Actors tab, open that character's sheet, click the weapon you want to attack with, open the Chat tab, and only then click attack. As a GM, this can get rather tedious, and I've taken to just rolling manually with the /roll command instead.

It would be neater if one could directly roll attacks and damage on the character sheet, without having to post a link to the weapon in question in the chat.

This could be achieved by adding attack/damage roll buttons into the "item-properties" box which is added to "item-flexrow" when it becomes "item-flexrow expanded".
This way, one could click a weapon entry in a character sheet to expand it, and then get buttons to roll attacks and damage, and only those rolls would get posted to the chat.

One could also have some sort of "roll attack" and/or "roll damage" button added directly to "item-flexrow", which would then always be visible, but this might look cluttered - especially if one has many weapons on one character sheet.

**Comment by wildj79** [comment]
I was actually considering this earlier this morning. The PF2e system does this, and it probably wouldn't be to hard to add.

**Comment by wildj79** [comment]
Fixed in PR #35
