### ISSUE TITLE
More open Starship sheet features

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#308]
With the recent introduction of alternate BP rules for starships, it would be good to have some means to use them in the foundry sheet.

My main thoughts are ways to edit the max BP stat. The modifier menu doesn't seem to currently have options for the Starship sheet, so perhaps adding those would be one way to go. at the very least, it would open options for other similar issues.

**Comment by rrenna** [comment]
The next release will have optional Galactic Trade rules. This will allow you to store BPs in your starships as currency. It also increases the max BP per level by 5%.
