### ISSUE TITLE
Unable to add weapons to starship character sheets

### ISSUE THREAD

**Issue by HubbeKing** [wildj79/foundryvtt-starfinder#32]
There's no option to add entries to the "Weapons" tab on the starship character sheet, and dragging an item from the equipment compendium onto the sheet causes the actor sheet to become un-openable.

**Comment by HubbeKing** [comment]
The following error is thrown to the browser console when I try to drag a weapon onto a starship sheet:
`TypeError: item.data.mount is undefined starship.js:138:17​`

**Comment by wildj79** [comment]
Ah, this issue, #27 . There is an issue with the system where it will allow players to add invalid item types to a starship. You shouldn't be able to add something like an "Azimuth laser pistol" for example. The only valid items types allowed should be starship weapons. If you could, in the actor tab in the side bar, right click on the ship and "Export Data". Then attached the `json` file that is produced to this ticket so I can take a look at it. If you're adventurous, you could open the file and check the `items` array and remove any non starshipWeapon items that might be in there. If you do this, make the changes, save the file, then right click on the actor in the sidebar and "Import Data".

I'm aware of the other issue as well. There won't be a fix for it in the next release, but I'll make sure that the release after that allows adding weapons manually.

**Comment by HubbeKing** [comment]
Attached a zipped json (github didn't like me attaching a json file directly) of a starship actor that I dragged a non-valid item onto.

[fvtt-Actor-Hippocampus.zip](https://github.com/wildj79/foundryvtt-starfinder/files/4623353/fvtt-Actor-Hippocampus.zip)

**Comment by wildj79** [comment]
OK, re-import this back into your actor and you should be able to open the actor's sheet again. And remember, you should only put Starship weapons on a Starship. There are none in the compendium at the moment, so that might be where some of the confusion comes in. For now, you'll have to create the item in the Items side bar and then drag those to the ship.
[fvtt-Actor-Hippocampus.zip](https://github.com/wildj79/foundryvtt-starfinder/files/4623578/fvtt-Actor-Hippocampus.zip)

**Comment by HubbeKing** [comment]
Many thanks! The starship sheet really should have the same function the NPC and character sheets have, where you can just create owned items directly on the sheet. Makes it much easier to quickly add weapons.

**Comment by wildj79** [comment]
Fixed. Will be out in the next release (which will hopefully be sometime this week. no promises though).

**Comment by wildj79** [comment]
Fixed in PR #35
