### ISSUE TITLE
Personal Upgrades

### ISSUE THREAD

**Issue by reubzilla** [wildj79/foundryvtt-starfinder#354]
Personal Upgrades are missing from equipment.

Ability Crystal (Magic), MK 1
Ability Crystal (Magic), MK 2
Ability Crystal (Magic), MK 3
Synaptic Accelerators (Technology), MK 1
Synaptic Accelerators (Technology), MK 2
Synaptic Accelerators (Technology), MK 3	
Synergizing Symbiote (Hybrid), MK 1	
Synergizing Symbiote (Hybrid), MK 2	
Synergizing Symbiote (Hybrid), MK 3

**Comment by ThroughlyDruxy** [comment]
All 9 items have been added. Report can be closed.
