### ISSUE TITLE
Spinal Struts copied from Speed Suspension

### ISSUE THREAD

**Issue by RevCivic** [wildj79/foundryvtt-starfinder#357]
The verbiage for Spinal Struts Augmentation looks as if it was copied directly from Speed Suspension.

Spinal Struts also follow a different naming convention (minimal, standard, reinforced) rather than (minimal, standard, complete)

![image](https://user-images.githubusercontent.com/22403423/113304434-07fff580-92d0-11eb-8b84-98ea2cc92f3e.png)

**Comment by ThroughlyDruxy** [comment]
Spinal Struts Complete was removed from the compendium as it doens't appear anywhere else. Seems like it was just copied from Speed Suspension and only the title was chanced. Report can be closed.
