### ISSUE TITLE
Icon Theme Typo

### ISSUE THREAD

**Issue by OtmicusRX** [wildj79/foundryvtt-starfinder#361]
The Icon Theme's ability: "Theme Knowledge (1st)" has a typo.
Currently it reads:

"[...] When attempting a Profession or Culture check to recall knowledge about other icons of your profession or details about your profession’s cultural aspects, **_increase_** the DC by 5."

It should read:

"[...] _**reduce**_ the DC by 5."

**Comment by ThroughlyDruxy** [comment]
Corrected and submitted PR.

**Comment by wildj79** [comment]
Fixed for the next release.
