### ISSUE TITLE
Cannot reference class level as a modifier inside the Weapon Specialisation feat.

### ISSUE THREAD

**Issue by Brandedahall** [wildj79/foundryvtt-starfinder#382]
When adding @classes.solarian.levels as a modifier to the Weapon Specialisation feat, it throws an error stating that the class level: "is not present in the provided roll data".

The modifier works if it is added directly to a weapon itself though.
@details.level.value works if I add it to the feat.

I have restarted my own browser, the GM has restarted their server as well and it still persists.

**Comment by ThroughlyDruxy** [comment]
Is this still an issue? I've recently tried it and it works. If it still isn't working for you check the spelling and make sure the modifier is applying to the correct weapon type.
