### ISSUE TITLE
[BUG] ( v0.11.0.0 beta ) - rollAttack / rollDamage returns Undefined

### ISSUE THREAD

**Issue by Nachtrose** [wildj79/foundryvtt-starfinder#393]
Since the dice roll rework for the new version i can `await` a dice roll. But when i try to use the returned value/object(?) it is always `undefined`. When asking around i was told, that it usually works returning a roll object if the roll was actually made or returning `null` if the roll window was closed without rolling dice.

Example code for usage:
``` (async ()=> {
  let a1 = await item.rollAttack({disableDamageAfterAttack: true});
  ui.notifications.info(a1);
  if (a1===null) return;
...```

**Comment by TimToxopeus** [comment]
This has been resolved well enough for now. Future implementation could involve figuring out how to make it return a roll, but for now this is okay.
