### ISSUE TITLE
Conditions can't be toggled off 0.11.2

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#398]
Hello

When activating a condition and subsequently deactivating it a SECOND time (using the checkboxes on the Actor Modifier sheet) the condition can sometimes not be removed and the following type of error is thrown:

```
foundry.js:1246 Uncaught (in promise) Error: The key soGQIhaktKXiMgy5 does not exist in the EmbeddedCollection Collection
    at Map.get (/C:/Program%20Files/…/collection.mjs:106)
    at ServerDatabaseBackend._updateEmbeddedDocuments (/C:/Program%20Files/…erver-backend.mjs:1)
    at ServerDatabaseBackend.update (/C:/Program%20Files/…act/backend.mjs:153)
    at async Socket.handleEvent (/C:/Program%20Files/…erver/sockets.mjs:1)
```

Step to reproduce:

- Empty Starfinder world, no modules, create a blank actor
- Go to Modifier sheet, activate a condition (ex.  Grappled)
- Deactivate the same condition
- Activate the condition a second time
- Deactivate the condition a second time
- Error is thrown, game requires a refresh

Toggling any other condition after the first does not trigger the error, only the second activation/deactivation of the same condition triggers this behavior.

Upon refreshing foundry (F5) the condition is removed from the GUI, but its effects remain applied until you do so. Effectively this means the game has to be "rebooted" everytime you want to remove a condition a second time from a player.

**Comment by TimToxopeus** [comment]
After much digging, it appears to be an issue in Foundry Core, not the system. Will keep this ticket open for future monitoring.

**Comment by LebombJames** [comment]
Can confirm that this still occurs on 0.8.7, SF version 0.11.3.

**Comment by TimToxopeus** [comment]
After spending the better part of a couple of days trying to figure it out, and also running into it once with the statblock parser, I finally figured out that it was the iteration over the tokens and adjusting the condition icon there, that caused the issue.

While I was refactoring here anyway, I also took the opportunity to move the setCondition function into the actor class, and creating a hook for modules and macros to work with.
