### ISSUE TITLE
Starship Armor Undefined

### ISSUE THREAD

**Issue by thes33** [wildj79/foundryvtt-starfinder#401]
![image](https://user-images.githubusercontent.com/12416750/120710905-58d4cb80-c484-11eb-80c9-20d580c0e1d5.png)

Starship Armor is now listed as an 'undefined' value.

**Comment by TimToxopeus** [comment]
This has already been fixed and is awaiting release.

**Comment by thes33** [comment]
Great!  Thanks for the quick response.
