### ISSUE TITLE
Players no longer able to open item containers in latest update

### ISSUE THREAD

**Issue by supernovajm** [wildj79/foundryvtt-starfinder#406]
Foundry version: 0.8.6
SFRPG version: 0.11.3

Even with GM logged in, players are no longer able to open any containers, and are unable to drag containers to the map.

replication steps:
* create a container
* drag container to map
* have player try to open container while GM is logged in

replication steps v2:
* login as player while GM is logged in
* attempt to drag an item from inventory to the map

https://user-images.githubusercontent.com/24704061/121519500-c7071a00-c9bf-11eb-952f-8f582a5c8b14.mp4

**Comment by TimToxopeus** [comment]
That was a little gnarly to fix, but it is fixed!
