### ISSUE TITLE
Duplicate Items vanish when removed from a container

### ISSUE THREAD

**Issue by supernovajm** [wildj79/foundryvtt-starfinder#407]
Foundry version: 0.8.6
SFRPG version: 0.11.3

When creating a container with duplicate items, if the items were dragged from the compendium, the container will show multiple copies, but they will all be removed when any one of them is dragged out of the container.

Once the item has been placed in a character's inventory, it stops exhibiting this behavior.

replication steps:
* create a new container on the map
* drag 2+ of the same item from the compendium
* open the container and remove one of the duplicate items (delete, move to player, move to map)

https://user-images.githubusercontent.com/24704061/121520401-dc307880-c9c0-11eb-8015-0d36ef981c21.mp4

**Comment by TimToxopeus** [comment]
Fixed, the underlying issue was that everything had the same id which made some systems a little too happy to delete duplicates. :-)
