### ISSUE TITLE
Some Starship Actions not working

### ISSUE THREAD

**Issue by FireclawDrake** [wildj79/foundryvtt-starfinder#408]
Hey there,

While some Starship actions are working, some throw errors like this: 
```
    Uncaught (in promise) TypeError: rollResult.roll.results is undefined
        useStarshipAction https://fireclawdrake.foundryserver.com/systems/sfrpg/module/actor/actor.js:1311
```

**Comment by TimToxopeus** [comment]
This is already fixed for the upcoming release.
A short term work-around is to go to system settings, and set the "Starship Actions Critical Effect" to either always or never.
