### ISSUE TITLE
Starship actions won't roll

### ISSUE THREAD

**Issue by tophertalks** [wildj79/foundryvtt-starfinder#409]
Using Version 0.11.3, many of the starship action options do not roll, throwing the following error:

`TypeError: Cannot read property '0' of undefined at ActorSFRPG.useStarshipAction(actor.js:1311)  
useStarshipAction @ actor.js.1311`

Seems to be happening for any action with a set DC such as Maneuver, Stunt, Divert, Hold it Together, etc

**Comment by TimToxopeus** [comment]
Duplicate of #408 

This is already fixed for the upcoming release.
A short term work-around is to go to system settings, and set the "Starship Actions Critical Effect" to either always or never.
