### ISSUE TITLE
Proper Spell levels usage.

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#412]
Currently the Spell slot usage selection is set for the way systems like D&D handle slot usage. Upscaling the slot.
However, with Starfinder instead using a downcasting system, the spell slot usage selection should reflect that.
e.g. If I have a multi-level spell at 3rd level, I should be able to select slot levels 1 or 2 as well as 3.
As it's currently, I can only select upward of the spell's set level. This makes it slightly awkward as either I have to put the spell at the highest level I know it, then manually lower the used slot. Or I have to note somewhere the spell is actually of a higher level then I may have placed it for usage.

**Comment by TimToxopeus** [comment]
Proper spell level usage has been implemented for the Starfinder v0.14 release.
