### ISSUE TITLE
Negative dexterity modifiers break item sheets

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#414]
Hello,

**Summary**

Whenever an item on an actor sheet who's item level (tested with Weapon and Armor) - the characters dexterity bonus == 0 the item sheet breaks and the tabs become unresponsive.

Video of this bug in action: https://streamable.com/i1q0ig

**Steps to reproduce**

Foundry 0.8.7, empty world, no mods.

1. Create actor
2. Drag level 1 item  "Skipshot pistol, tactical" from compendium to character sheet
3. Edit character sheet to have a dex modifier of -1, in the video I do this by dragging the Nuar race (which has a -1 to dex) to the sheet, but any other way works too.
4. Try to edit the item on the actor, the item will open but all tabs are frozen
5. Lower or raise the dex modifier or the item level to make the problem go away, all combinations work except where they add to zero

Possible culprit that uses both values: Save DC calculation on items.

**Comment by wildj79** [comment]
Should be fixed in the current release.
