### ISSUE TITLE
Newly created weapons don't have capacity and usage section

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#417]
Hello,

Summary: when creating weapons manually (i.e not dragging them from the compendium) in Foundry 0.8.8 with SFRPG 0.11.4 the newly created weapons don't have the "Capacity and Usage" section. The header is present but none of the controls are available.

![Capture](https://user-images.githubusercontent.com/6693164/123508267-9cc78480-d66e-11eb-8e45-dc6f159f9ee1.PNG)

**Comment by TimToxopeus** [comment]
I have removed the check that enabled/disabled the entire section, either items support it or they don't, no need to add additional checks. This should mean it is always visible for freshly created items.
