### ISSUE TITLE
No "Weapon X has no ammunition left!" for charge based weapons.

### ISSUE THREAD

**Issue by WaterpoloBlock** [wildj79/foundryvtt-starfinder#420]
I noticed that, if I have the Ammunition Type set to Charges (For any weapon), it will allow me to fire a weapon even if my current ammo is at 0. 

Where’s, if I set it to any other ammo type and try to fire it while my current ammo is at 0; it’ll give me the prompt that “ Weapon X has no ammunition left!

**Comment by TimToxopeus** [comment]
Fixed! :) It was using the old capacity field data rather than the appropriate helper method.
