### ISSUE TITLE
setCondition not checking character sheet condition box

### ISSUE THREAD

**Issue by ILikeCoolThings** [wildj79/foundryvtt-starfinder#421]
Using the setCondition function in a macro does not check the box in the character sheet. It does apply the icon and apply debuffs though.

Way to reproduce:
Use below macro:
[setCondition-Example.txt](https://github.com/wildj79/foundryvtt-starfinder/files/6759048/setCondition-Example.txt)

Apply any condition to a player or NPC token, and see the box not check on condition tab.

**Comment by TimToxopeus** [comment]
Simplified macro for testing purposes:
```
const actor = canvas.tokens.controlled[0].actor;
const hasBleeding = actor.hasCondition("bleeding");
actor.setCondition("bleeding", !hasBleeding);
```

**Comment by TimToxopeus** [comment]
The setCondition function wasn't actually toggling the data field for the checkboxes. This has been rectified and will be available in the next release. :)

**Comment by ILikeCoolThings** [comment]
Nice, thanks!
