### ISSUE TITLE
Feature request: Set token vision for newly created tokens as enabled by default. 

### ISSUE THREAD

**Issue by Nachtrose** [wildj79/foundryvtt-starfinder#425]
Currently you have manually enable vision ( "Token has vision" ) for each token created.
Making it enabled by default would save some time, clicks and possibly headscratches, when you wonder why the PCs do not see anything again ;-)

**Comment by wildj79** [comment]
There is actually a core Token Configuration setting in foundry to have token vision turned on automatically. Considering that there is already an option to override this, I don't see a reason to override it further at the system level.

To access it, click on the gear icon on the side bar, click on "Configure Settings", then on the "Core Settings" tab, click on "Configure Default Token Settings" button.
