### ISSUE TITLE
Speed calculation does not account for armor penalty

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#426]
Hello,

I'm on the latest development commit (0818934) as of this ticket and I've noticed that the speed calculation does not take into account the penalty from armor. 

Steps to reproduce:

1. Create character, give it some speed
2. Equip armor from compendium such as "Golemforged Plating"
3. Speed is not adjusted with the armor penalty from the plating

**Comment by TimToxopeus** [comment]
Fixed! :)
