### ISSUE TITLE
Issue: Solarian attunement tracker causes slowness in combat

### ISSUE THREAD

**Issue by ILikeCoolThings** [wildj79/foundryvtt-starfinder#427]
This was talked about in the SFRPG discord, but this is the official issue.

**Observations**: 

- When the issue happens, the combat tracker flashes constantly, browsers go to 100% CPU, and the app seemingly locks up until the player disconnects.
- Also, non solarian players get the below warning. The actor ID is the solarian: 
"message":"User player lacks permission to update Actor [eTbEwsbo6bTeyuZr]","stack":"Error: User player lacks permission to update Actor [eTbEwsbo6bTeyuZr]\n    at ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/database/backend/server-backend.mjs:1:2940)\n    at async Socket.handleEvent (file:///C:/Program%20Files/FoundryVTT/resources/app/dist/server/sockets.mjs:1:568)"

**Steps to reproduce**:
- Add Solarian plus other players to combat tracker (Only the solarian is needed)
- Login as GM in foundry client 
--This does nothing. The GM can add steps to the attunement tracker with no problem
- Login as a player (Non solarian) in browser
-- This does nothing besides throw the update error
- Login as the solarian in browser
-- This is when the issue starts. The issue appears in a few ways:
--- Flashing combat tracker
--- High CPU in the browser
--- Slowness in repsonse and dragging on all players including GM

**To stop the issue once it starts**:
- Close the window where the solarian is logged in
- Disable the attunement tracker 
- End combat

Let me know if you need any logs.

**Comment by TimToxopeus** [comment]
The Solarian tracker has been rewritten from scratch for the upcoming release. This should tackle all of these issues. Read the changelist for the v0.14 release to see the steps the solarian players will have to take to re-enable their tracking.
