### ISSUE TITLE
Save effects break after first roll until refresh

### ISSUE THREAD

**Issue by Redpisces** [wildj79/foundryvtt-starfinder#429]
Using any save effect breaks the chat cards of all save effects rolled by client after it, until the client refreshes

![image](https://user-images.githubusercontent.com/489107/127777140-16033973-d832-4371-bad4-79f82e8a3160.png)

--after refresh--
![image](https://user-images.githubusercontent.com/489107/127777155-9f098f34-7bb1-4d42-bb27-0bde6879183d.png)

Foundry Version: 0.8.8
System Version: 0.11.4
All modules disabled

**Comment by wildj79** [comment]
Thanks for the ticket! This is actually a known issue, and should be corrected in the next release.

**Comment by wildj79** [comment]
Should be fixed in the current release.
