### ISSUE TITLE
Display names incorrect for certain attributes

### ISSUE THREAD

**Issue by supernovajm** [wildj79/foundryvtt-starfinder#441]
On the character sheets, fields like Damage Resistance, Damage Vulnerabilities, and Damage Immunities are displaying as SFRPG.DamRes, SFRPG.DamVuln, SFRPG.DamImm respectively

![image](https://user-images.githubusercontent.com/24704061/131925437-3c569315-cf96-468b-af51-0b79d327bda5.png)

**Comment by wildj79** [comment]
Thanks for pointing this out. I had changed some of the keys in the localization files. Apparently I missed updating  some of the references in the system.

**Comment by wildj79** [comment]
Fixed in commit ada63f89320267897475269badd97553f7fb09f0 and has already been released in v0.13.1.
