### ISSUE TITLE
incorrect compendium link in space gobelin compendium

### ISSUE THREAD

**Issue by theksi** [wildj79/foundryvtt-starfinder#452]
Hello,
I am sharing this incorrect link I have found in the space gobelin (race) compendium
>Over time, the goblins learned to build weapons and armor from scavenged parts, though many of their efforts are @Compendium[sfrpg.conditions.XeRGqHVtcZ7vsgJ0]{Prone} to exploding at the slightest provocation.

Prone in this case doesn't refer the to `prone`status , the description should be

>Over time, the goblins learned to build weapons and armor from scavenged parts, though many of their efforts are prone to exploding at the slightest provocation.

**Comment by TimToxopeus** [comment]
Fixed by pull request 466 :)
