### ISSUE TITLE
Disabling actor resource causes character sheet to not open

### ISSUE THREAD

**Issue by ILikeCoolThings** [wildj79/foundryvtt-starfinder#456]
This is easily reproducible by creating a actor resource with any value, any range, and any mode.

Once you uncheck the enabled checkbox at the top and close the character sheet, you will no longer be able to open the character sheet.

The only way to fix it is to edit the JSON and set the enabled status back to true.

**Comment by TimToxopeus** [comment]
Fixed for SFRPG v0.15.0 release.
