### ISSUE TITLE
Situational damage modifiers break roll if nothing is checked

### ISSUE THREAD

**Issue by ILikeCoolThings** [wildj79/foundryvtt-starfinder#462]
Spoke about this in the discord but if you have a situational damage modifier like from a Solarian crystal, and you do not check the damage modifier, the roll will not occur and the below error is produced:
Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression "6  +  9  +  2  + "
[Detected 1 package: system:sfrpg]
    at Function.safeEval (foundry.js:5614)
    at SFRPGRoll._evaluateTotal (foundry.js:5540)
    at SFRPGRoll._evaluate (foundry.js:5491)
    at async http:/localhost:30000/systems/sfrpg/module/dice.js:618
    at async http:/localhost:30000/systems
/sfrpg/module/rolls/rolltree.js:102

Seems like when nothing is checked, a random + is being added to the end.

If the modifier is changed to constant, there is no error. 
If you check the modifier, the roll continues.

I have attached my player's JSON where you can try it with any attack and by not checking the modifier.
[fvtt-Actor-yulia-al-moser.txt](https://github.com/wildj79/foundryvtt-starfinder/files/7557891/fvtt-Actor-yulia-al-moser.txt)

**Comment by TimToxopeus** [comment]
I just created a new character, imported this json, tried to roll, and it worked fine on my end. Though I was testing on the latest version, while I'm not aware of any changes to the rolling, it is possible there is a difference.

It doesn't seem to include the crystals at all, how do I activate them?

**Comment by ILikeCoolThings** [comment]
It is triggered in the damage roll, where the situational damage modifier for the crystal comes into play. I just did the same thing in a world with no modules and I was able to repro.

I can record my screen, or give more info if it helps. Though i know I wasn't the only one having the issue.
