### ISSUE TITLE
Variable spell level not working for damage or other formula

### ISSUE THREAD

**Issue by Bagenholm** [wildj79/foundryvtt-starfinder#465]
When rolling damage, or other formula, on a spell with a Variable Spell Level, @item.level is always the spell's top level, instead of the level the spell is cast at.

**Comment by TimToxopeus** [comment]
Confirmed, I'll see if I can figure out how to solve this one, as this is actually a difficult case.

**Comment by TimToxopeus** [comment]
Done, thanks for the report. :)
