### ISSUE TITLE
Fix Weapon Specialization Class feature for classes other than mechanic

### ISSUE THREAD

**Issue by tiapfy** [wildj79/foundryvtt-starfinder#468]
Title. At the moment it seems that the only "Weapon Specialization" class feature working as it should is "Weapon Specialization (Mechanic)". I'd also appreciate a lot if Weapon Specialization could be more easily integrated into the sheet, like the proficiency system for example.
(If I missed some easy way to implement this or if this is already being worked on I'm sorry)

**Comment by Iankid** [comment]
Might be a (maybe distant) future endeavor. But at least for now, you can simply edit the "Mechanic" specialization to reflect the other classes. I think it's only marked as mechanic to give an example of how it should work.

**Comment by tiapfy** [comment]
Yeah that’s what I’ve been doing but to me it’s just strange that a pretty basic feature (it’s something that everybody gets at third level) isn’t implemented more easily, that’s all.

**Comment by wildj79** [comment]
If someone wants to step up to the plate and submit a pull request for it, that would be great. Otherwise, it might be awhile before this gets addressed.

**Comment by Iankid** [comment]
I'll go ahead and start working on this.

**Comment by Iankid** [comment]
Updates in the Dev branch, if we want to close this.

**Comment by arthurfferreira** [comment]
This is already fixed, right? I'm not seeing the pull request there anymore and the feat for all classes are available in the system

**Comment by TimToxopeus** [comment]
Closing it. :)
