### ISSUE TITLE
Wrong character in Icon

### ISSUE THREAD

**Issue by MicheleDelliVeneri** [wildj79/foundryvtt-starfinder#471]
Change /development/src/icons/spells/t%C3%A9l%C3%A9kinetic_projectile.png to /development/src/icons/spells/telekinetic_projectile.png

**Comment by wildj79** [comment]
Fixed in https://github.com/wildj79/foundryvtt-starfinder/commit/9052dc6aa127e16871f523ebe140943ef57b3c7f. It'll be in the next release, but no timeframe on that.
