### ISSUE TITLE
Spell save DC not showing up in chat card

### ISSUE THREAD

**Issue by Bagenholm** [wildj79/foundryvtt-starfinder#475]
Casting it with no lvl 3 spell slots available, and the spell doesn't show up in the chat card at all (can't check/uncheck Consume Spell Slot).

No saving throw showing up on the chat card:
Casting while Consume Spell Slot is checked, and no spell DC set, no save in chat card.
Casting while it's not checked, spell DC shows up.
Casting while it's checked, and there's only a number in the input field, spell DC shows up.
When any kind of math is added, it doesn't show up. 10 works. 10+1 doesn't. @item.level works, 1+@item.level doesn't.

**Comment by TimToxopeus** [comment]
Caused by an asynchronous order of operations issue. Fixed! :)
