### ISSUE TITLE
Unable to cast any spells,

### ISSUE THREAD

**Issue by zero127** [wildj79/foundryvtt-starfinder#482]
```
Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[Detected 1 package: system:sfrpg]
    at Function.all (<anonymous>)
    at ActorSFRPG.useSpell (actor.js:210)
```

This error appears x3 in console, spell slots aren't consumed i think because the code ceases here. I do have addons, but i had the same error when I created a new game with new actors and freshly imported data. 

Spell / Setup used in this is a Vesk (low gravity) Technomancer Roboticist casting lv 1 Supercharge Weapon. I seem to be unable to cast any spells at all. Feel free to reach out on discord Dan#6804 if you want to see our setup or if that can be useful! Thanks :)

**Comment by wildj79** [comment]
Typically, we see this type of issue with some kind of data corruption, like a character that has starship weapons or some other item that it shouldn’t have attached. If you could, export the character, zip up the json file, and then link it to this issue. Then we can take a look at it. At the very least, it’ll give us a known bad actor to test with.

**Comment by wildj79** [comment]
I've just been informed by @TimToxopeus that this was a known issue that should be fixed in the next release. So, keep an eye out for it, it should be out in the next day or two.

**Comment by zero127** [comment]
Oh nice! okay cool! Thanks so much. have a merry christmas/holiday! Ill leave these here just in case. one is my players character, the other is a fresh one from a fresh game. Sounds like you already have it taken care of but due diligence, want to do my part. :) Thanks again for all the work put into this. We're excited to start our first game next year.
https://1drv.ms/u/s!Ag7bc7G5rEk8gssqxFabwqih2alofw?e=KkEAl2
https://1drv.ms/u/s!Ag7bc7G5rEk8gssrsExkoAra4-sELA?e=6nQ2FA

**Comment by wildj79** [comment]
This should be fixed in the current release.
