### ISSUE TITLE
Incorrect feat description: Opening Volley (Ex) (1st)

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#484]
Current:
You gain Opening Volley as a bonus feat. If you already have this feat, choose a bonus combat feat instead. At 9th level, you can use Opening Volley on both your first and second turns in combat.

Should Be: 
Your ranged assault leaves your foe disoriented and vulnerable to your next melee attack.

**Benefit**: Whenever you deal damage to an opponent with a ranged attack on your first turn in a combat, you gain a +2 circumstance bonus to your next melee attack roll against that opponent. This melee attack must occur before the end of your next turn.

**Comment by wildj79** [comment]
Hmm.... Either this was already fixed in a previous PR, or you've got an old checkout for the development branch, because it looks fine in development currently. Closing for now. If it turns out its still wrong, we can reopen.

**Comment by CptTwinkie** [comment]
It looks good locally now as well. I can confirm that both the class feature and the combat feat are correct. My remaining concern is how I saw them displayed the same before.
