### ISSUE TITLE
Suggestion: NPC2 layout

### ISSUE THREAD

**Issue by CptTwinkie** [wildj79/foundryvtt-starfinder#485]
My suggestion is to display more speed information in the attributes tab. 

- Initiative could be reduced to 1/4 width allowing speed to be 3/4
- It seems there are 5 speed values and a special string
- It should be possible to get those 5 in there horizontally
  - Flying could be displayed with its maneuverability appended to its value
  - Bonus: if values of 0 can be hidden there should be plenty of room to have the special string displayed with ellipsis overflow (this may require a property that generates a custom array)

**Comment by TimToxopeus** [comment]
Good suggestion, this box now automatically sizes to fit the vertical space required.
![image](https://user-images.githubusercontent.com/14136558/147588824-2d7b0bd4-98a1-436f-8acc-95954836e5ac.png)
