### ISSUE TITLE
Spell Casting wont work level one or above with anything other than save selected.

### ISSUE THREAD

**Issue by xanstin** [wildj79/foundryvtt-starfinder#486]
I have tried removing all modules, rebuilding the spells, creating the characters over. But if I cast Jolting Surge or Magic Missile it doesnt use the slot or show up in chat. I am using the built in spells and created ones. The exact spell works with just changing it to level 0. 

For example when I cast/roll magic missile it throws these errors. This is a brand new PC created for this purpose

![image](https://user-images.githubusercontent.com/26841771/147594938-c11fd9f5-25dc-4af2-9348-582054856103.png)

The same spell if I just change level to 0 works fine and posts the chat card with damage roll box

**Comment by TimToxopeus** [comment]
Have you updated to Starfinder v0.16.1 yet? That should have fixed this issue.

**Comment by xanstin** [comment]
I am on 16.1 per Forge

**Comment by xanstin** [comment]
Uninstalled/Reinstalled the ruleset. Problem persists.

**Comment by TimToxopeus** [comment]
I've been able to reproduce it, it seems to be caused by the saving throw being unset. Thanks for the report, I'll get right on fixing that. :-)

In the mean time, you can work around it by either setting a bogus saving throw, or clearing the action type.

**Comment by xanstin** [comment]
Yeah I didn't see a way to put saving throw "none" in the drop down with negates or adjacent fields. I can report that work around does work.

Thank you for the prompt response and tireless work.

**Comment by TimToxopeus** [comment]
Fixed it, ready for the next release. :-)
