### ISSUE TITLE
Starfinder version 0.16.1 may not be compatible with Foundry VTT versions newer than 9

### ISSUE THREAD

**Issue by b0nj0m0n** [wildj79/foundryvtt-starfinder#492]
Trying to install on forge-vtt.com. Using Foundry version 9. Tried using both the "install" button and pasting the URL from readme.md into the json address. Does foundryvtt-starfinder support version 9?

**Comment by wildj79** [comment]
Starfinder works fine with v9. You might need to reach out to the support folks on the forge for specific help.

**Comment by b0nj0m0n** [comment]
Confirmed - thanks James. Gave me an error but it seems to be working.
