### ISSUE TITLE
Unable To Drag Any Items Or Abilities To Hotbar

### ISSUE THREAD

**Issue by symbiote-42** [wildj79/foundryvtt-starfinder#495]
Foundry Version 9 Build 238
Starfinder 0.16.1
Host OS: Windows 10 Pro
Browsers: Chrome and Firefox (both)
Modules: None, fresh world with no modules and a fresh install of Foundry-Starfinder

I'm happy to invite you to my server to see the bug in action. Cheers and thanks!

**Comment by supernovajm** [comment]
Stack Trace

```
sfrpg.js:405 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
[Detected 1 package: system:sfrpg]
    at createItemMacro (sfrpg.js:405)
    at sfrpg.js:369
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at Hotbar._onDrop (foundry.js:52128)
    at DragDrop.callback (foundry.js:44100)
    at DragDrop._handleDrop (foundry.js:44151)
createItemMacro @ sfrpg.js:405
(anonymous) @ sfrpg.js:369
_call @ foundry.js:294
call @ foundry.js:279
_onDrop @ foundry.js:52128
callback @ foundry.js:44100
_handleDrop @ foundry.js:44151
```

**Comment by wildj79** [comment]
Looks like we missed a deprecation notice from foundry core. It's an easy fix, and will be out in the next release (no solid date on when that might be, though).

**Comment by wildj79** [comment]
Fixed in current release.

**Comment by symbiote-42** [comment]
Y'all rock! Thanks for everything you do!
