### ISSUE TITLE
Add AON Link Button to All Entities

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#50]
I believe a very important step to creating a system for a Paizo game is to take full advantage of the OGL, and the officially-supported online SRD.

To accomodate this as best possible, there should definitely be a Source hyperlink which takes you to the Archives of Nethys SF SRD for any Entity that possesses one.

Ideally, the current 'Source' category should be specify the page number of the source in addition - but also by a hyperlink that takes you to the AON SF SRD page of the item (which discloses the specific source page as well).

The sooner this can be done, the sooner a fully comprehensive compendium can be created and most easily maintained by any end user.

**Comment by wildj79** [comment]
I'm not entirely sold on this. First off, I disagree that this is "important" or "necessary" for the system to be complete. For those items that already exist in the compendium, most of them pull there description text from AoN already (this is a manual process; I don't have a magic parser to do this automatically). And, most of the relevant game data is already in the item. From my perspective, the time needed to add items to the compendiums stays the same whether this exists or not. So, this is what I would like from you:

* Give me an explanation of how you envision this to function. Is it just a link that opens up in a new tab in the players browser, or are you expecting this to open a window within foundry. The former could easily be added to the description text that already exists; the latter would take programming to implement. Is there any other functionality that isn't explicitly stated in your issue that you'd like to see.
* Please provide some real world use cases where this would be useful or helpful. Explain what kind of workflow you expect and how this will make things better or easier for the player or GM.

So you know, I'm not entirely against the idea, I just need a little convincing that this is worth the time and effort needed to implement it.

**Comment by JayBWalker** [comment]
I spoke with the guys from the PF2 Module and they tell me the CUP document sadly forbids the direct linkage of AONSRD articles from within your distributed project.
Otherwise, they would have been adding AON links within their compendiums to the relevant articles already.

In lieu of this restriction I would instead recommend something similar but less specific, though I'll make a new Issue about it shortly.
