### ISSUE TITLE
In-app Archives of Nethys SRD Search Tool

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#51]
Unfortunately, adding direct AONSRD hyperlinks within distributed Foundry mods (even if not for profit) is disallowed by the CUP license.
However, something to serve this purpose is still highly desirable.

I suggest: A Search Tool, similar to [Search Anywhere](https://gitlab.com/riccisi/foundryvtt-search-anywhere).

It would ideally work to allow users within FVTT to search AONSRD from within the app, the query opening in a new browser tab utilising AONSRD's already-existing Search functions.

The benefits of this is that it would provide are all fundamentally to do with community solidarity, and ease of transition to Starfinder in Foundry for folks coming from elsewhere.
Being the official SRD for Paizo ttrpgs, AON is the device that everyone uses and trusts as a first port of call (outside of the actual books themselves). To keep this connection would make it very comfortable for people wanting to get into Starfinder from elsewhere, and teach good habits to anyone experiencing SF via FVTT as their first.

Additionally, if an Entity's accuracy in an SF compendium were ever called into question then the ability to search it up on AON for clarification quickly and in-app would be very useful.
This kind of thing happens multiple times per session, in my experience. I'm very proficient in the use of the books themselves but not everyone is going to have them, or the time to learn them back to front.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] In-app Archives of Nethys SRD search tool](https://trello.com/c/Vdkmsg1n/29-feat-in-app-archives-of-nethys-srd-search-tool)
