### ISSUE TITLE
[Bug] Damage calculation simplifying references

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#515]
Formulas with the Damage field on items, become simplified when the item is opened.

E.g. Formula "(@Classes.solarian.levels)d8" will calculate correctly, even after changing solarian level.
But opening the item the damage formula is in, even just to the description tab, will simplify the formula to current base values
"1d8","2d8" etc.

**Comment by TimToxopeus** [comment]
Fixed!
