### ISSUE TITLE
Custom chat cards do not work with wildcard tokens

### ISSUE THREAD

**Issue by Vallant85** [wildj79/foundryvtt-starfinder#529]
Stumbled upon a bug while using wildcards with a custom chat card.
While using custom cards, they do not display the token image when used as a wildcard

![Chatcardbug](https://user-images.githubusercontent.com/98958424/152640259-e06f56c6-1982-486b-a473-ac0eb843001f.jpeg)

**Comment by TimToxopeus** [comment]
Fixed! :)
