### ISSUE TITLE
Feature request: A toggle to set default roll method.

### ISSUE THREAD

**Issue by whoek92** [wildj79/foundryvtt-starfinder#53]
Currently you need to hold Shift to perform a 'quick' attack/damage roll, A toggle in the system setting that sets 'quick roll' as default would be a nice QoL feature.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Toggle to set default roll method](https://trello.com/c/jaUFE152/28-feat-toggle-to-set-default-roll-method)

**Comment by wildj79** [comment]
Added in https://github.com/wildj79/foundryvtt-starfinder/commit/b503fa5669792d429208e38c2d7d3e78d2e68f70. Will be in next release.
