### ISSUE TITLE
Saving throw formulas on feats stop working

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#534]
For some reason, saving throws from feat items are no longer working. If it's a fresh install of the SF system, it works once, then no longer after. instead just showing "save" in the text. This bug is in the Dev branch.
![savesbroke](https://user-images.githubusercontent.com/60759323/152666142-95f8a036-9cd8-42b2-a816-f148f792d87a.png)

**Comment by TimToxopeus** [comment]
Fixes have been made! :D

**Comment by Iankid** [comment]
Just tested, still not working
