### ISSUE TITLE
Spells with saves not being sent to chat

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#542]
If a spell is set with a saving throw, and is set as a 1+ level spell, it does not go through.

Error code:

actor.js:227 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[Detected 1 package: system:sfrpg]
    at Function.all (<anonymous>)
    at ActorSFRPG.useSpell (actor.js:227)
useSpell @ actor.js:227
Promise.then (async)
useSpell @ actor.js:255
await in useSpell (async)
_onItemRoll @ base.js:633
(anonymous) @ base.js:239
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

actor.js:227 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[Detected 1 package: system:sfrpg]
    at Function.all (<anonymous>)
    at ActorSFRPG.useSpell (actor.js:227)
useSpell @ actor.js:227
Promise.then (async)
useSpell @ actor.js:269
await in useSpell (async)
_onItemRoll @ base.js:633
(anonymous) @ base.js:239
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

actor.js:227 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[Detected 1 package: system:sfrpg]
    at Function.all (<anonymous>)
    at ActorSFRPG.useSpell (actor.js:227)
useSpell @ actor.js:227

**Comment by TimToxopeus** [comment]
Fixed
