### ISSUE TITLE
Initiative roll does not add modifier

### ISSUE THREAD

**Issue by DM7700** [wildj79/foundryvtt-starfinder#543]
When doing an initiative roll through the combat tracker, the modifier is not correctly added to the roll.

**Comment by C4M3R0N808** [comment]
This is just my opinion... But if while we're fixing this it's an "easy" enough addition, I think incorporating the initiative "tie-breaker" automatically would be great. So rather than d20+init it would become d20+(1.01×init). Of course this may be a feat in itself to try to add so we'll see lol.

**Comment by TimToxopeus** [comment]
Yeah I would like to separate that out into a different issue, I'd rather address bugs and feature requests as separate things because it'll keep things cleaner. :)

**Comment by TimToxopeus** [comment]
Fixed this issue!
