### ISSUE TITLE
Issue: Spell damage does not work in 18.0

### ISSUE THREAD

**Issue by ILikeCoolThings** [wildj79/foundryvtt-starfinder#545]
Spells in 18.0 seem to be broken.

After disabling the spell save to work around #542, the damage doesn't populate for each spell. Also, I do not see any damage settings in the spell details. Before 18.0, you can roll damage form the generated chat card.

18:
![image](https://user-images.githubusercontent.com/54457140/153632601-425920f1-67d6-448f-a94e-1aa3e0f506e8.png)

17:
![image](https://user-images.githubusercontent.com/54457140/153632255-45e07fc2-a1e3-4725-a85d-af9230b664f6.png)

**Comment by Iankid** [comment]
Noted spells seem to be set as "saving throw" spells right out the compendium, which don't include a damage roll.
