### ISSUE TITLE
Request: Initiative Tie Breaker

### ISSUE THREAD

**Issue by C4M3R0N808** [wildj79/foundryvtt-starfinder#547]
If we could incorporate the initiative "tie-breaker" automatically, that would be great. So rather than d20+init it would become d20+(1.01×init). If this isn't feasible or something then I understand haha. It's a convenience thing for sure.

**Comment by TimToxopeus** [comment]
I can add the easy version; one where the situational modifiers to initiative aren't included, only the raw dex score and constant modifiers.
