### ISSUE TITLE
Allow the save DC field to take a roll formula instead of it autocalculating it

### ISSUE THREAD

**Issue by decad7never** [wildj79/foundryvtt-starfinder#55]
Hello,

Just an improvment to manage saving throw related to skills or attributes check. 

for example on this item 

> Restraining spinneret
> Starfinder Armory p.87

> Your hand conceals a rapid-acting spinneret you can use to entangle an opponent with sticky webbing if you succeed at a melee attack against their EAC. You can add your Dexterity modifier to this attack roll rather than your Strength modifier. If you hit, your target gains the entangled condition for 1d4 rounds. Ending the entangled condition requires the target to succeed at an Acrobatics check or Strength check as a move action (DC = 10 + half your level + your Dexterity modifier). Once you have used your restraining spinneret, you can’t use it again until you’ve rested for 10 minutes to regain Stamina Points, though you can spend 1 Resolve Point at any point to recharge it immediately.

And another weapons, amelioration and so one, exist with the same way. Also for some cases, for spell.

It can be a good thing to make this case possible.

We have the same request to manage DC like that => DC = 10 + half your level + your Dexterity modifier (today i can't manage half your level to display the right DC)

Thanks ;)

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Allow the save DC filed to take a roll formula instead of it auto calculating it](https://trello.com/c/DOtkw1We/41-feat-allow-the-save-dc-filed-to-take-a-roll-formula-instead-of-it-auto-calculating-it)

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Spells - CL and DC should be displayed somewhere for spells and it should be possible to have modifiers for them](https://trello.com/c/oQxFlopB/49-feat-spells-cl-and-dc-should-be-displayed-somewhere-for-spells-and-it-should-be-possible-to-have-modifiers-for-them)

**Comment by wildj79** [comment]
Recent updates have fixed this. Closing this for now.
