### ISSUE TITLE
Rolls for specific profession do not mention the profession in chatlog

### ISSUE THREAD

**Issue by mkahvi** [wildj79/foundryvtt-starfinder#607]
Repro:
- Add profession skill
- Roll that profession
- Note how chatlog does not mention the added profession at all, just unspecific profession.

**Comment by wildj79** [comment]
Yep, I can totally confirm this one.

**Comment by wildj79** [comment]
Fixed in [f53e182](https://github.com/wildj79/foundryvtt-starfinder/commit/f52e182c113552dc259318e12c5a83afc97e1bd7) and will be in the next release.
