### ISSUE TITLE
Pressing enter in stamina or HP input fields has odd behaviour

### ISSUE THREAD

**Issue by mkahvi** [wildj79/foundryvtt-starfinder#636]
Instead of submitting the stamina/HP change, it gives add skill dialog.

**Comment by Iankid** [comment]
This has existed a long time. Not sure if it's a "bug", as you can just click anywhere after typing a new value. But I do agree at least it's unintuitive.

**Comment by wildj79** [comment]
@Iankid Oh, it's definitely a bug. One that I've know about for some time, but have never been able to track down (I'm surprised that it has taken this long for someone to report it). It's some kind of weird interaction with foundry and it's keybindings. I generally don't like to point fingers at upstream, but this one is most likely an issue in core foundry. We don't even have anything listening for `keyup`, `keydown`, or `keypress` events.

**Comment by mkahvi** [comment]
I don't think this is core foundry bug, but rather normal HTML form behaviour.

You have add skill as a <button>, and I think for some reason it is intercepting the enter key and treating it as form submission despite not having type="submit".

I'd recommend removing the <button> element and replacing it with something custom with click listener.

**Comment by wildj79** [comment]
Yep, that was the issue. It seems setting an explicit `type="button"` does the trick, so it was a pretty easy fix. Fixed in 69cfef877ce99e22cbcc5021c197688f1a1e62a9
