### ISSUE TITLE
The Custom Conditons for the System are not Linking to their Compendium Journal Entries via CUB automatically.

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#67]
As titled. They should _probably_ automatically link to their Journal (c) Pages, but are not. Might be a mod issue however, rather than a System issue.

**Comment by wildj79** [comment]
I'm going to make a blanket statement here that applies to all issues concerning modules and what the starfinder system is willing to do to support them. The starfinder system is _not_ going to guarantee support for any specific module nor is it going to add code for the sole purpose of adding said support. Minor changes that make it easier for mods, in general, to work effectively and don't significantly effect the functionality of the system will be considered. Conversely, the use of a modules specific code to make it work with starfinder will not be considered. In my mind, the onus for support for specific systems lies with the module author, and not the systems author. With that in mind, if you'd like to see starfinder support in specific modules, you would need to reach out to the author of those modules and request that they add the needed support.

With that being said, if you haven't done this already, you'll need to reach out to `@errational#2007` on discord or submit an issue to the CUB issue board.
