### ISSUE TITLE
I can not open character actor sheet.

### ISSUE THREAD

**Issue by Sisthedog** [wildj79/foundryvtt-starfinder#688]
whenever I make a new playable character the character sheet window does not pop up and won't pop up if I double-click on the character name
![Screenshot (2)](https://user-images.githubusercontent.com/108322494/176323677-d2d93a33-32aa-49e2-a2e0-92a2eaa18129.png)
.

**Comment by wildj79** [comment]
Open up the settings window by clicking on the gear icon in the sidebar, then click on the "Configure Settings" button. Click on the "System Settings" tab, then scroll to the bottom of the page. Find the "Currency Locale" setting and set it to be _exactly_ `en-US`. This should fix the issue.

**Comment by Sisthedog** [comment]
thank you so much for this
