### ISSUE TITLE
Adding notes to items or starship sheets breaks the avatar image

### ISSUE THREAD

**Issue by HubbeKing** [wildj79/foundryvtt-starfinder#71]
Adding text to the notes section on a starship sheet causes the avatar image of the sheet to break.

Adding text to an item breaks the image on the item.

This might be caused by VTTA tokenizer, but I am unsure as I haven't had time to extensively test - setting the image again fixes it.

**Comment by wildj79** [comment]
Please disable all modules and verify that it's not a module. If it's not, we'll continue to troubleshoot from there.

**Comment by HubbeKing** [comment]
Okay, issue still happens even with all modules disabled.

Foundry pops up a warning saying the image doesn't exist - it looks like adding text to notes removes everything after the last slash in the avatar image path?

Before editing notes of a starship - the avatar image path is `suns/sunrise-maiden-token.png`
After editing notes - clicking the now broken avatar image pops up a warning saying "Directory 'suns' does not exist."

**Comment by wildj79** [comment]
Ok, I'll have to take a look.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Adding notes to items or starship sheets breaks the avatar image](https://trello.com/c/0KLqXUZj/33-bugz-adding-notes-to-items-or-starship-sheets-breaks-the-avatar-image)

**Comment by TimToxopeus** [comment]
I am unable to reproduce this issue. And I've not heard of this issue happening to anyone else in the past half year.

Might it have been a FoundryVTT issue? I know Atropos has made multiple changes to how file access is handled in v0.7, and maybe even in v0.6, I'm not sure which version of FoundryVTT was used when this issue was reported.

**Comment by HubbeKing** [comment]
Yeah, this seems to have been fixed in Foundry since I first discovered it in... 0.5.7, I think? I'll go ahead and close the issue.
