### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by krobibero** [wildj79/foundryvtt-starfinder#8]
Hey, glad someone has been working on this!

I tried downloading and installing your module on my Linux install of FVTT 0.4.3.  I have the files in the _starfinder_ folder under _modules_ however Step 2 I'm getting "Incorrect manifest file https://raw.githubusercontent.com/wildj79/foundryvtt-starfinder/master/system.json for module installation. Requires module.json"

I'm not a dev but have a fair amount of IT experience.  Not sure if this is a FVTT issue or specific to your module.

**Comment by wildj79** [comment]
As stated in discord, this is not a module but a system. So to install, go to the "Game Systems" tab, click on the "Install System" button on the bottom of the screen, then paste https://raw.githubusercontent.com/wildj79/foundryvtt-starfinder/master/system.json into the "Manifest URL" input box.
![image](https://user-images.githubusercontent.com/2126857/71117524-e858c280-219b-11ea-8712-11ad220a659f.png)
