### ISSUE TITLE
Hyperlinking text with certain formatting in HTML Text Fields does not display correctly - Picture Inside

### ISSUE THREAD

**Issue by JayBWalker** [wildj79/foundryvtt-starfinder#88]
As titled. Currently when you use certain text formatting within descriptions it will break the links and throw out the formatting entirely when viewed outside of the Edit box.

Edit Box: https://media.discordapp.net/attachments/526670777941229570/728869576044970004/unknown.png?width=830&height=512
Result: https://media.discordapp.net/attachments/526670777941229570/728869636472307730/unknown.png?width=789&height=515

**Comment by wildj79** [comment]
This is a known issue within foundry. I want to say this was addressed in the current version (v0.6.5), but I could be wrong. Either way, it's not a starfinder specific issues. Closing since it's an upstream issue.
