### ISSUE TITLE
Deleting a skill removes the skill from the sheet permanently with no way to restore it.

### ISSUE THREAD

**Issue by TimToxopeus** [wildj79/foundryvtt-starfinder#91]
If you right-click a skill in your skills list on both the Character or NPC sheets, you get a little popup with some settings to tweak. One of them is a checkbox "delete?". If you check it and submit, the skill is permanently removed from the sheet with no way to restore it. The skill is still listed under "Toggle Skills" on the NPC sheet, but toggling the skill does not restore it either.

**Comment by wildj79** [comment]
So, that box only shows for GM users. It's meant to be used to remove accidentally added profession skills. It also allows for more control over home brewing skills. Considering that this is a GM only available option, I'm pretty content to leave this as is. GM's should know better, and if they don't it's there own damn fault ;). The other option would be to remove the box all together, which I'm fine with as well.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Deleting a skill removes the skill from the sheet permanently with no way to restore it.](https://trello.com/c/II2jMvNz/35-bugz-deleting-a-skill-removes-the-skill-from-the-sheet-permanently-with-no-way-to-restore-it)

**Comment by TimToxopeus** [comment]
Fixed it by only allowing custom profession skills to be deleted.
